config/routes.rb
Rails.application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'users#destroy', as: 'logout'

  resources :users
  resources :sessions

  root to: 'users#index'
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  belongs_to :user
  belongs_to :role
end

app/models/player.rb
class Player < ActiveRecord::Base
  has_and_belongs_to_many :users

  validates :name, presence: true
  validates :school, presence: true

end

app/models/role.rb
class Role < ActiveRecord::Base
  has_one :admin
  validates :title, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  has_and_belongs_to_many :players
  has_one :admin

  validates :name, presence: true
  validates :address, presence: true
  validates :phone, presence: true
  validates :email, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  private
    def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
    end

    helper_method :current_user

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to :root, notice: 'Logged In!'
    else
      flash.now.alert = "Email or password is invalid"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to :root, notice: 'Logged out!'
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to :root, notice: 'Thank you for signing up!'
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation, :phone, :address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GHLL</title>
  <link href='http://fonts.googleapis.com/css?family=Roboto:400,300,500,500italic,700,900' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-fixed-top navbar-default" role="navigation">
    <div class="container">
      <div class="naviHeader">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navHeaderCollapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
        </button>
        <div class="collapse navbar-collapse navHeaderCollapse">
            <ul class="nav navbar-nav navbar-left">
              <li><a href="/">GHLL Team Communication</a></li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
              <% if current_user %>
               <li><%= link_to current_user.name, user_path(current_user) %></li>
               <li><%= link_to 'Logout', session_path('current'), method: 'delete' %></li>
              <% else %>
                <li><%= link_to 'Login', new_session_path %></li>
                <li><%= link_to 'Register', new_user_path %><li>
              <% end %>
            </ul>
        </div>
      </div>
    </div>
  </nav>

  <div id="wrapper">
    <%= yield %>
  </div>

</body>
</html>

app/views/users/index.html.erb
  <% @users.each do |user| %>
    <%= link_to user.name, user_path(user) %>
  <% end %>

app/views/users/new.html.erb
<div class="container-fluid">

  <div class="row">
    <div class="col-md-6">
      <h1>Sign Up </h1>

      <%= form_for @user, role: 'form' do |f| %>
        <% if @user.errors.any? %>
          <div class="error_messages">
            <h2>Form is invalid</h2>
            <ul>
              <% @user.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <%= f.label :name, 'Full Name:', class: 'sr-only' %>
          <%= f.text_field :name, placeholder: 'Full Name', class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :email, 'Email:', class: 'sr-only' %>
          <%= f.text_field :email, placeholder: 'Email', class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :phone, 'Phone Number:', class: 'sr-only' %>
          <%= f.text_field :phone, placeholder: 'Phone Number', class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :address, 'Address:', class: 'sr-only' %>
          <%= f.text_area :address, placeholder: 'Address', class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :password, 'Password:', class: 'sr-only' %>
          <%= f.password_field :password, placeholder: 'Password', class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :password_confirmation, 'Password Confirm:', class: 'sr-only' %>
          <%= f.password_field :password_confirmation, placeholder: 'Password Confirm', class: 'form-control' %>
        </div>
        <%= f.submit "Register", :class => 'btn btn-info' %>
      <% end %>

    </div>
  </div>

</div>

app/views/users/show.html.erb
<%= @user.name %>